# https://wiki.hypr.land/Configuring/Variables/#animations

animations {
    enabled = true

    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1

    animation = global,        1, 10,    default
    animation = border,        1, 5.3,   easeOutQuint
    animation = windows,       1, 3,   easeOutQuint
    animation = windowsIn,     1, 4.0,   easeOutQuint, popin 87%
    animation = windowsOut,    1, 1.5,   linear,       popin 87%
    animation = fadeIn,        1, 1.7,   almostLinear
    animation = fadeOut,       1, 1.4,   almostLinear
    animation = fade,          1, 3.0,   quick
    animation = layers,        1, 3.8,   easeOutQuint
    animation = layersIn,      1, 4.0,   easeOutQuint, fade
    animation = layersOut,     1, 1.5,   linear,       fade
    animation = workspaces,    1, 3,   default, slide
    animation = zoomFactor,    1, 7,     quick
    animation = specialWorkspace, 1, 3, easeInOutCubic, slideInvert
}