#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# Walpaper
exec-once = swww-daemon
exec = swww img ~/Pictures/Wallpapers/wall1.png

# Status bar
exec-once = waybar

# HyprIdle
exec-once = hypridle

# Notification Daemon
exec-once = dunst

# Clipboard man.
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Network applet
exec-once = nm-applet &

# Polkit authentication agent
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

exec-once = $terminal
# exec-once = firefox


