#################
### WALLPAPER ###
#################

preload = /home/stoaxcode/Pictures/Wallpapers/wall1.png
wallpaper = DP-1,/home/stoaxcode/Pictures/Wallpapers/wall1.png

# Or solid color:
# wallpaper = ,#1A1B26

splash = false
ipc = off