background {
    monitor =
    path = ~/Pictures/Wallpapers/wall1.png
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.7
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"<span foreground='#00FFFF'>%H:%M</span>")"
    color = rgba(0, 255, 255, 1.0)
    font_size = 120
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 200
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 5
    shadow_color = rgba(0, 162, 255, 0.5)
}