general {
    gaps_in = 6
    gaps_out = 12
    border_size = 2
    layout = dwindle
}

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
    force_split = 2
    smart_split = false
    smart_resizing = true
    no_gaps_when_only = 0
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
    new_on_top = false
    mfact = 0.65
    orientation = left
    always_center_master = false
}
