# Workspace specific behavior
workspace = 1, rounding:false, border:false
workspace = 2, gapsin:3, gapsout:6
workspace = 3, rounding:true, shadow:true
workspace = 4, monitor:DP-1
workspace = 5, on-created-empty:firefox

# workspace for sractpads
workspace = special:scratch-term, gapsin:0, gapsout:0
workspace = special:scratch-serial, gapsin:0, gapsout:0